"""Build docs/sft/RESULTS.md from results/sft/.

    python scripts/phase3_report.py

Every number comes from the saved result files (and the fixed evaluation prompts in
data/instruct/eval_prompts.jsonl for the gold stories); nothing is typed in by hand.
"""

import json
import statistics
import textwrap
from pathlib import Path

from forge.instruct import WORD, check, load_jsonl, normalize, prompt, repetition

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results" / "sft"
OUT = ROOT / "docs" / "sft"
PROMPTS = ROOT / "data" / "instruct" / "eval_prompts.jsonl"


def read(name):
    return json.loads((RESULTS / name).read_text(encoding="utf-8"))


def pct(value):
    return "n/a" if value is None else f"{100 * value:.1f}%"


def story_stats(stories):
    return {
        "words": statistics.mean(len(WORD.findall(normalize(s))) for s in stories),
        "repetition": statistics.mean(repetition(s) for s in stories),
    }


def verdict(result, finished):
    parts = []
    if "words" in result:
        hits = result["words"]["hits"]
        parts.append(f"{sum(hits)} of {len(hits)} required words")
    if "sentence" in result:
        parts.append("sentence " + ("included" if result["sentence"] else "missing"))
    if "dialogue" in result:
        parts.append("dialogue " + ("present" if result["dialogue"] else "missing"))
    ending = "ended" if finished else "did not end"
    return f"Check: {', '.join(parts)}; reward {result['reward']:.2f}; the story {ending}."


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    records = {r["id"]: r for r in load_jsonl(PROMPTS)}
    evals = {name: read(f"{name}_eval.json") for name in ("base_L", "sft_L", "gold")}
    samples = {name: load_jsonl(RESULTS / f"{name}_samples.jsonl") for name in ("base_L", "sft_L")}
    fluency = read("fluency.json")["files"]
    fluency = {
        "gold": fluency["eval_prompts.jsonl"],
        "base_L": fluency["base_L_samples.jsonl"],
        "sft_L": fluency["sft_L_samples.jsonl"],
    }
    stats = {name: story_stats([row["story"] for row in rows]) for name, rows in samples.items()}
    stats["gold"] = story_stats([r["story"] for r in records.values()])
    train = read("train_summary.json")
    curve = [json.loads(line) for line in (RESULTS / "training_curve.jsonl").open()]
    dropped = read("first_eval_dropped_requests.json")
    gold_check = json.loads((ROOT / "results" / "instruct" / "gold_check.json").read_text())
    shuffled = gold_check["shuffled_story"]["satisfied"]["rate"]
    dataset = train["dataset"]
    run = train["run_config"]
    seen = run["steps"] * run["batch"] * run["accumulate"] * run["context"]
    columns = ("base_L", "sft_L", "gold")

    def row(label, values):
        return f"| {label} | " + " | ".join(values) + " |"

    def constraint(key):
        return [pct(evals[c]["per_constraint"][key]["rate"]) for c in columns]

    b, s = evals["base_L"], evals["sft_L"]
    lines = [
        "# Phase 3: supervised fine-tuning results",
        "",
        "The pretrained 33.6M-parameter L model fine-tuned on TinyStories-Instruct: "
        f"{dataset['train_examples']:,} examples ({dataset['train_tokens'] / 1e6:.1f}M "
        "tokens), each an instruction prompt followed by its story and an end-of-text "
        "token, with the loss on the story and end-of-text tokens only. "
        f"{run['steps']:,} steps of {run['batch'] * run['accumulate'] * run['context']:,} "
        f"tokens ({seen / dataset['train_tokens']:.2f} passes over the data), peak "
        f"learning rate {run['lr']:g} with {run['warmup']} warmup steps and cosine decay "
        f"to {run['min_lr_ratio']:.0%}, bf16. Generated by `scripts/phase3_report.py` "
        "from `results/sft/`.",
        "",
        "## Instruction following",
        "",
        f"The {b['prompts']} fixed held-out prompts (drawn from the validation split, "
        "never trained on), "
        f"{b['samples_per_prompt']:.0f} samples each at temperature 0.8 and top-p 0.95. A "
        "sample satisfies its prompt when every checkable constraint passes: each "
        "required word appears (inflections allowed), the given sentence appears "
        "verbatim, and there is quoted speech when Dialogue is requested. The gold column "
        "scores the dataset's own story for each prompt with the same checks.",
        "",
        "| | Base L | SFT L | Gold stories |",
        "|---|---:|---:|---:|",
        row(
            "**All constraints met**",
            [f"**{pct(evals[c]['satisfied']['rate'])}**" for c in columns],
        ),
        row(
            "Mean reward (fraction of constraints met)",
            [f"{evals[c]['mean_reward']:.3f}" for c in columns],
        ),
        row("Required words found (per word)", constraint("word_recall")),
        row("All required words found", constraint("all_words")),
        row("Given sentence included", constraint("sentence")),
        row("Dialogue when requested", constraint("dialogue")),
        row("Story ended with end-of-text", [pct(evals[c]["finished_rate"]) for c in columns]),
        row(
            "Fluency: nats/token under pretrained L",
            [f"{fluency[c]['nats_per_token']:.3f}" for c in columns],
        ),
        row("Mean length (words)", [f"{stats[c]['words']:.0f}" for c in columns]),
        row("Repeated word 4-grams", [pct(stats[c]["repetition"]) for c in columns]),
        "",
        "Constraint counts: "
        + ", ".join(
            f"{b['per_constraint'][key]['n'] // b['samples_per_prompt']:.0f} prompts with " + label
            for key, label in (
                ("all_words", "required words"),
                ("sentence", "a given sentence"),
                ("dialogue", "Dialogue"),
            )
        )
        + f". For scale, a gold story scored against a different prompt's constraints "
        f"satisfies them {pct(shuffled)} of the time (whole validation split, "
        "`results/instruct/gold_check.json`).",
        "",
        f"SFT raised the share of fully satisfied samples from {pct(b['satisfied']['rate'])} "
        f"to {pct(s['satisfied']['rate'])} and the mean reward from {b['mean_reward']:.3f} "
        f"to {s['mean_reward']:.3f}. Dialogue is almost always there when asked for "
        f"({pct(s['per_constraint']['dialogue']['rate'])}), and most required words appear "
        f"({pct(s['per_constraint']['word_recall']['rate'])} of them), but all of a "
        f"prompt's words only in {pct(s['per_constraint']['all_words']['rate'])} of samples, "
        f"and the given sentence in just {pct(s['per_constraint']['sentence']['rate'])}: "
        "copying a sentence verbatim is the constraint SFT learned least.",
        "",
        "Fluency is each story's loss under the pretrained L, scored on its own as in "
        "pretraining. It compares models sampled the same way, not models against the "
        "gold text: sampling at temperature 0.8 with top-p favors probable tokens, which "
        f"is why SFT samples ({fluency['sft_L']['nats_per_token']:.3f}) score lower than "
        f"the human-written gold stories ({fluency['gold']['nats_per_token']:.3f}). Base L "
        f"samples ({fluency['base_L']['nats_per_token']:.3f}) are short continuations of "
        "an instruction format it never saw, not stories.",
        "",
        "## Training",
        "",
        f"Validation loss on the story tokens of {dataset['val_examples']:,} held-out "
        f"examples fell from {train['initial_val_loss_this_session']:.4f} (the base model) "
        f"to {train['final_val_loss']:.4f} nats/token ({train['val_bits_per_byte']:.4f} "
        "bits per byte of story text):",
        "",
        "| Step | " + " | ".join(str(p["step"]) for p in curve if p["step"] in STEPS) + " |",
        "|---|" + "---:|" * sum(p["step"] in STEPS for p in curve),
        "| Validation loss | "
        + " | ".join(f"{p['val_loss']:.4f}" for p in curve if p["step"] in STEPS)
        + " |",
        "",
        f"Training took {train['seconds_this_session'] / 60:.0f} minutes on the RTX 4050, "
        f"including {train['thermal_pauses']} thermal-guard pauses "
        f"({train['thermal_paused_seconds'] / 60:.0f} minutes) at 85 °C.",
        "",
        "## What went wrong first",
        "",
        "The first evaluation reported "
        f"{pct(dropped['sft_L']['reported_satisfied_rate'])} satisfied for SFT L, with only "
        f"{pct(dropped['sft_L']['reported_finished_rate'])} of stories finished. Nearly all "
        "of the unfinished ones were empty strings. The generation command queued all "
        f"{dropped['sft_L']['rows']:,} requests before the first engine step, and the "
        "engine, written for serving, rejects requests beyond a 1,024-request queue and "
        "drops requests that wait more than 60 s. "
        f"{dropped['sft_L']['empty_rows']:,} SFT samples and "
        f"{dropped['base_L']['empty_rows']:,} base samples came back empty and were scored "
        "as failures. Offline generation now uses an engine without those limits and "
        "raises if any request fails, with a regression test that makes every engine step "
        "take 100 s. Counts: `results/sft/first_eval_dropped_requests.json`.",
        "",
        "## Samples from SFT L",
        "",
        "The first two evaluation prompts, sample 0 of each (not cherry-picked):",
        "",
    ]
    for sample in [r for r in samples["sft_L"] if r["sample"] == 0][:2]:
        record = records[sample["id"]]
        lines += ["```text", prompt(record).rstrip()]
        for paragraph in sample["story"].split("\n"):
            lines += textwrap.wrap(paragraph, 88) or [""]
        lines += ["```", "", verdict(check(record, sample["story"]), sample["finished"]), ""]
    (OUT / "RESULTS.md").write_text("\n".join(lines), encoding="utf-8")
    print(
        json.dumps(
            {
                c: {"satisfied": evals[c]["satisfied"]["rate"], "reward": evals[c]["mean_reward"]}
                for c in columns
            }
        )
    )


STEPS = (100, 200, 400, 600, 800, 1000, 1200, 1400)

if __name__ == "__main__":
    main()
